name: CI
run-name: CI for ${{ github.ref }}

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: '1.7B'

  test:
    needs: build
    uses: ./.github/workflows/test.yaml
    with:
      version: '1.7B'
